services:
  nginx:
    image: hybula/lookingglass-nginx:1
    container_name: lg-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    network_mode: host
    restart: unless-stopped

  php-fpm:
    image: hybula/lookingglass-php:1
    container_name: lg-php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      # For a better reference as to what these variables do, check out 'config.dist.php' or 'docker/php-fpm/src/config.php'.
      # Please replace them with values that are relevant to your situation!
      LOCATION: Location
      FACILITY: Facility
      FACILITY_URL: http://localhost/
      IPV4_ADDRESS: 127.0.0.1
      IPV6_ADDRESS: ::1
      MAPS_QUERY: Amsterdam
      # Pass these variables with any arbitrary value to disable the respective block.
      # DISABLE_BLOCK_NETWORK: 'true'
      # DISABLE_BLOCK_LOOKINGGLASS: 'true'
      # DISABLE_BLOCK_SPEEDTEST: 'true'
      # Uncomment to enable the custom block, which you can use to add something custom to the LG.
      # ENABLE_CUSTOM_BLOCK: 'true'
      # Uncomment if you require visitors to accept the Terms of Use; the value should be a link to the terms.
      # LG_TERMS: http://localhost/

  # iperf3:
  #   image: networkstatic/iperf3:latest
  #   container_name: lg-iperf3
  #   network_mode: host
  #   command: -s
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
